version: '3.5'

networks: 
    frontend:
    backend:

services:
    back:
        image: jtwa551/dockerhy_part1_backend:latest
        environment:
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=user
            - DB_PASSWORD=example
            - DB_HOST=db
            - DB_NAME=POSTGRES_USER
        ports: 
            - 8000:8000
        volumes: 
            - ./logs.txt:/backend-example-docker-master/logs.txt
        container_name: B9000
        depends_on:
            - db
        networks: 
            - backend
    front:
        image: jtwa551/dockerhy_part1_frontend:latest        
        ports:
            - 5000:5000
        container_name: F9000
        networks: 
            - frontend
    redis:
        image: redis
        command: ["redis-server", "--appendonly", "yes"]        
        volumes: 
            - ./data:/data
        container_name: CH9000
        networks: 
            - backend
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=POSTGRES_USER
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes: 
            - ./database:/var/lib/postgresql/data/pgdata
        container_name: DB9000
        networks: 
            - backend
    nginx:
        image: nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - front
            - back
        container_name: NX9000
        networks: 
            - frontend
            - backend
