version: '3.5'

services: 
    training:
        build: ./ml-kurkkumopo-training
        image: ml-kurkkumopo-training
        container_name: training_container
        volumes: 
            - files:/src/model
            - images:/src/imgs
    
    backend:
        build: ./ml-kurkkumopo-backend
        image: ml-kurkkumopo-backend
        ports: 
            - 5000:5000
        container_name: backend_container
        volumes: 
            - files:/src/model
    
    frontend:
        build: ./ml-kurkkumopo-frontend
        image: ml-kurkkumopo-frontend
        ports:
            - 8080:3000
        container_name: frontend_container

volumes: 
    images:
    files:
        