version: '3.5'

services:
    back:
        image: jtwa551/dockerhy_part1_backend:latest
        environment:
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
            - REDIS_PORT=6379
            - DB_USERNAME=user
            - DB_PASSWORD=example
            - DB_HOST=db
            - DB_NAME=POSTGRES_USER
        ports: 
            - 8000:8000
        volumes: 
            - ./logs.txt:/backend-example-docker-master/logs.txt
        container_name: B9000
        depends_on:
            - db
    front:
        image: jtwa551/dockerhy_part1_frontend
        environment: 
            - API_URL=http://localhost:8000
        ports:
            - 5000:5000
        container_name: F9000
    redis:
        image: redis
        container_name: CH9000
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=POSTGRES_USER
        container_name: DB9000
